# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-FlasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "adv-it-flack-application-packages"
  EB_APPLICATION_NAME      : "MyFlack"
  EB_ENVIRONMENT_NAME      : "MyFlask-env"
  DEPLOY_PACKAGE_NAME      : "flack_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "us-west-2"

on:
  push:
    branches: [ master ]

jobs:  
  my-ci-part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone repo 
      uses: actions/checkout@v2

    - name: Create ZIP deployment package
      run: zip -r  ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
 
